name: RDP-Fixed
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Tailscale
        shell: powershell
        run: |
          Set-ExecutionPolicy RemoteSigned -scope Process -Force
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
          Start-Process -FilePath "tailscale-setup.exe" -ArgumentList "/quiet", "/norestart" -Wait
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
      - name: Keep Alive
        run: |
          Write-Host "PC is Ready!"
          $n = 360
          while($n -gt 0) { Start-Sleep -Seconds 60; $n-- }
